### ISSUE TITLE
Medioex Modülünde Hata #1

### ISSUE THREAD

**Issue by fahrettine** [nejdetckenobi/pymedioex#4]
Merhaba,
RPi4te (Raspbian Buster) modülü test etme amacıyla sadece aşağıdaki kodları çalıştırıyorum.
import medioex
medioex.do_di_init()
Aşağıdaki hatayı alıyorum:
Backend terminated or disconnected.Fatal Python error: Segmentation fault
Sorun ne olabilir? Teşekkürler...

**Comment by nejdet-amani** [comment]
Merhaba, kullanıcınızın yetkisi olmayabilir. Bu repo yerine beyaz.net'in medioex modülünü takip etmek isteyebilirsiniz.

**Comment by nejdetckenobi** [comment]
Merhaba, kullanıcınızın yetkisi olmayabilir. 
Bu durumda kodunuzu sudo ile çalıştırmanız ya da kullanıcınızı dialout grubuna eklemelisiniz.

Bu repo yerine beyaz.net'in medioex modülünü takip etmek isteyebilirsiniz.
https://github.com/beyaznet/python-medioex-module
